### ISSUE TITLE
ImportError: No module named pyimg

### ISSUE THREAD

**Issue by xil3so** [Donearm/PyImagedownloader#1]
Thank you for great contribution and futher inspiration, although I have to admit I didn't manage to run this software, probably because I'm very inexperienced python user.

`python setup.py install` ended without apparent problems:

byte-compiling build/bdist.linux-i686/egg/pyimagedownloader/bellazon.py to bellazon.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying PyImagedownloader.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying PyImagedownloader.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying PyImagedownloader.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying PyImagedownloader.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying PyImagedownloader.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pyimagedownloader.runtests: module references **file**
creating 'dist/PyImagedownloader-1.6-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing PyImagedownloader-1.6-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg
Extracting PyImagedownloader-1.6-py2.7.egg to /usr/local/lib/python2.7/dist-packages
PyImagedownloader 1.6 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg
Processing dependencies for PyImagedownloader==1.6
Searching for lxml==3.5.0b1
Best match: lxml 3.5.0b1
Processing lxml-3.5.0b1-py2.7-linux-i686.egg
lxml 3.5.0b1 is already the active version in easy-install.pth

Checking /usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/ shows a list of files (all installed with very bad permissions and file ownership, but I think it's setup's.py issue) so after fixing it alltogether I've got:

running_as_user_or_root$ /usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/pyimagedownloader.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/pyimagedownloader.py", line 38, in <module>
    import savesource, imageshack, imagevenue, imagehaven, imagebam, \
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/imageshack.py", line 26, in <module>
    from pyimg import user_agent
ImportError: No module named pyimg

So I've checked this file and I see:
# importing config file variables

from pyimg import basedir, numprocs, debug, logfile, logmaxsize

According to Google: "No results found for python +pyimg" 

Given the mention in readme:
It also downloads images posted in one of the supported forum or sites
(see Supported Forum/Sites List) given that you have a valid login (user
- password) and put it in the config file (pyimg.py). Those supported
  are just what I regularly use, more could be added.

and .gitignore:
pyimg.py*

I think you could provide some kind of pyimg-py.dist showing HOW those values should be set (I mean, to provide examples) and, better, to use ~/.some_dotfile style to keep configuration (and create initial one on themselves)...

...because fixing every single thing like this spoils all fun:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/pyimagedownloader.py", line 428, in <module>
    download_url(url, basedir, options.embed, options.poster)
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/pyimagedownloader.py", line 310, in download_url
    logger.info("Downloading from %s" % url[0])
IndexError: list index out of range

Etc. 
Thanks.

**Comment by Donearm** [comment]
There's [pyimg-example.py](PyImagedownloader/pyimagedownloader/pyimg-example.py), which you should rename to simply pyimg.py. Edit what you need there before, it should be self-explanatory. You are right about following more of a dotfiles standard but this software is very old and I haven't been maintaining it any more, sorry. Pull requests welcomed :)
