### ISSUE TITLE
Feature request: to respect HTTP*_PROXY shell variables and to add possibility to bind process to specific interface

### ISSUE THREAD

**Issue by xil3so** [Donearm/PyImagedownloader#3]
On a systems with few ways to access the Internet (and the default one being limited/throttled/denied) sometimes the only way to reach webservers is to provide proxy server.

On a multihomed systems there might be desirable to provide interface name or, at least, IP address for process to bind to -- e.g. to let process to download galleries using slower but unmetered link.

**Comment by Donearm** [comment]
I agree. However I think that due to Python's GIL this feature would be best to reserved for a future rewriting of PyImagedownloader in another language, probably Go. At this moment you should consider PyImagedownloader as "abandonware" due to lack of time/motivation.
